<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Coding question definition.
 *
 * @package     qtype_codejudge
 * @copyright   2026 IA Judge Contributors
 * @license     https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

global $CFG;
require_once($CFG->dirroot . '/question/type/questionbase.php');

/**
 * Question definition for code-based responses.
 */
class qtype_codejudge_question extends question_with_responses {

    /**
     * Normalise code text so quiz save/review comparisons are stable.
     *
     * @param string|null $code Raw code from the response array.
     * @return string
     */
    private function normalise_code_text(?string $code): string {
        $code = (string)$code;
        $code = str_replace(["\r\n", "\r"], "\n", $code);

        return $code;
    }

    /**
     * The question expects code and language data.
     *
     * @return array
     */
    public function get_expected_data(): array {
        return [
            'code' => PARAM_RAW,
            'language' => PARAM_ALPHANUMEXT,
        ];
    }

    /**
     * Use the manual grading behaviour until asynchronous evaluation is wired in.
     *
     * @param question_attempt $qa Question attempt.
     * @param string $preferredbehaviour Preferred behaviour.
     * @return question_behaviour
     */
    public function make_behaviour(question_attempt $qa, $preferredbehaviour) {
        return question_engine::make_behaviour('manualgraded', $qa, $preferredbehaviour);
    }

    /**
     * A response is complete when the code is not empty.
     *
     * @param array $response The submitted response.
     * @return bool
     */
    public function is_complete_response(array $response): bool {
        return trim($this->normalise_code_text($response['code'] ?? null)) !== '';
    }

    /**
     * A response is gradable when the code is present.
     *
     * @param array $response The submitted response.
     * @return bool
     */
    public function is_gradable_response(array $response): bool {
        return $this->is_complete_response($response);
    }

    /**
     * Summarise the response for review screens.
     *
     * @param array $response The submitted response.
     * @return string
     */
    public function summarise_response(array $response): string {
        $code = trim($this->normalise_code_text($response['code'] ?? null));
        if ($code === '') {
            return '';
        }

        return mb_substr($code, 0, 120);
    }

    /**
     * Rebuild a response from its summary.
     *
     * @param string $summary Summary generated by summarise_response().
     * @return array
     */
    public function un_summarise_response(string $summary): array {
        if ($summary === '') {
            return [];
        }

        return [
            'code' => $summary,
            'language' => self::get_default_language_for_restore(),
        ];
    }

    /**
     * Compare two responses.
     *
     * @param array $prevresponse Previous response.
     * @param array $newresponse New response.
     * @return bool
     */
    public function is_same_response(array $prevresponse, array $newresponse): bool {
        return $this->normalise_code_text($prevresponse['code'] ?? null) === $this->normalise_code_text($newresponse['code'] ?? null)
            && (string)($prevresponse['language'] ?? '') === (string)($newresponse['language'] ?? '');
    }

    /**
     * There is no canonical correct answer for a coding question.
     *
     * @return ?array
     */
    public function get_correct_response(): ?array {
        return null;
    }

    /**
     * Default language used when restoring a summarized response.
     *
     * @return string
     */
    private static function get_default_language_for_restore(): string {
        return \qtype_codejudge\local\language_helper::get_default();
    }
}
